package io.github.kitakkun.backintime.compiler.valuecontainer

import io.github.kitakkun.backintime.compiler.backend.ValueContainerClassInfo
import org.jetbrains.kotlin.javac.resolve.classId
import org.jetbrains.kotlin.name.Name
import org.jetbrains.kotlin.name.SpecialNames

val ValueContainerBuiltIns = listOf(
    ValueContainerClassInfo(
        classId = classId("androidx.lifecycle", "MutableLiveData"),
        capturedFunctionNames = listOf(
            Name.identifier("postValue"),
            Name.identifier("setValue"),
        ),
        getterFunctionName = Name.identifier("getValue"),
        setterFunctionName = Name.identifier("postValue"),
        preSetterFunctionNames = emptyList(),
        serializeItSelf = false,
        serializeAs = null,
    ),
    ValueContainerClassInfo(
        classId = classId("androidx.compose.runtime", "MutableState"),
        capturedFunctionNames = listOf(
            Name.guessByFirstCharacter("<set-value>"),
        ),
        getterFunctionName = Name.guessByFirstCharacter("<get-value>"),
        setterFunctionName = Name.guessByFirstCharacter("<set-value>"),
        preSetterFunctionNames = emptyList(),
        serializeItSelf = false,
        serializeAs = null,
    ),
    ValueContainerClassInfo(
        classId = classId("kotlinx.coroutines.flow", "MutableStateFlow"),
        capturedFunctionNames = listOf(
            Name.guessByFirstCharacter("<set-value>"),
            Name.identifier("update"),
            Name.identifier("updateAndGet"),
            Name.identifier("getAndUpdate"),
            Name.identifier("emit"),
            Name.identifier("tryEmit"),
        ),
        getterFunctionName = Name.guessByFirstCharacter("<get-value>"),
        setterFunctionName = Name.guessByFirstCharacter("<set-value>"),
        preSetterFunctionNames = emptyList(),
        serializeItSelf = false,
        serializeAs = null,
    ),
    ValueContainerClassInfo(
        classId = classId("kotlin.collections", "MutableList"),
        capturedFunctionNames = listOf(
            Name.identifier("add"),
            Name.identifier("addAll"),
            Name.identifier("clear"),
            Name.identifier("remove"),
            Name.identifier("removeAll"),
            Name.identifier("removeAt"),
            Name.identifier("set"),
            Name.identifier("replaceAll"),
        ),
        getterFunctionName = SpecialNames.THIS,
        setterFunctionName = Name.identifier("addAll"),
        preSetterFunctionNames = listOf(Name.identifier("clear")),
        serializeItSelf = true,
        serializeAs = null,
    ),
    ValueContainerClassInfo(
        classId = classId("kotlin.collections", "MutableSet"),
        capturedFunctionNames = listOf(
            Name.identifier("add"),
            Name.identifier("addAll"),
            Name.identifier("clear"),
            Name.identifier("remove"),
            Name.identifier("removeAll"),
        ),
        getterFunctionName = SpecialNames.THIS,
        setterFunctionName = Name.identifier("addAll"),
        preSetterFunctionNames = listOf(Name.identifier("clear")),
        serializeItSelf = true,
        serializeAs = null,
    ),
    ValueContainerClassInfo(
        classId = classId("kotlin.collections", "MutableMap"),
        capturedFunctionNames = listOf(
            Name.identifier("clear"),
            Name.identifier("put"),
            Name.identifier("putAll"),
            Name.identifier("remove"),
            Name.identifier("set"),
            Name.identifier("replace"),
            Name.identifier("replaceAll"),
        ),
        getterFunctionName = SpecialNames.THIS,
        setterFunctionName = Name.identifier("putAll"),
        preSetterFunctionNames = listOf(Name.identifier("clear")),
        serializeItSelf = true,
        serializeAs = null,
    ),
    ValueContainerClassInfo(
        classId = classId("androidx.compose.runtime", "MutableIntState"),
        capturedFunctionNames = listOf(
            Name.guessByFirstCharacter("<set-value>"),
            Name.guessByFirstCharacter("<set-intValue>"),
        ),
        getterFunctionName = Name.guessByFirstCharacter("<get-value>"),
        setterFunctionName = Name.guessByFirstCharacter("<set-value>"),
        preSetterFunctionNames = emptyList(),
        serializeItSelf = false,
        serializeAs = classId("kotlin", "Int"),
    ),
    ValueContainerClassInfo(
        classId = classId("androidx.compose.runtime", "MutableLongState"),
        capturedFunctionNames = listOf(
            Name.guessByFirstCharacter("<set-value>"),
            Name.guessByFirstCharacter("<set-longValue>"),
        ),
        getterFunctionName = Name.guessByFirstCharacter("<get-value>"),
        setterFunctionName = Name.guessByFirstCharacter("<set-value>"),
        preSetterFunctionNames = emptyList(),
        serializeItSelf = false,
        serializeAs = classId("kotlin", "Long"),
    ),
    ValueContainerClassInfo(
        classId = classId("androidx.compose.runtime", "MutableFloatState"),
        capturedFunctionNames = listOf(
            Name.guessByFirstCharacter("<set-value>"),
            Name.guessByFirstCharacter("<set-floatValue>"),
        ),
        getterFunctionName = Name.guessByFirstCharacter("<get-value>"),
        setterFunctionName = Name.guessByFirstCharacter("<set-value>"),
        preSetterFunctionNames = emptyList(),
        serializeItSelf = false,
        serializeAs = classId("kotlin", "Float"),
    ),
    ValueContainerClassInfo(
        classId = classId("androidx.compose.runtime", "MutableDoubleState"),
        capturedFunctionNames = listOf(
            Name.guessByFirstCharacter("<set-value>"),
            Name.guessByFirstCharacter("<set-doubleValue>"),
        ),
        getterFunctionName = Name.guessByFirstCharacter("<get-value>"),
        setterFunctionName = Name.guessByFirstCharacter("<set-value>"),
        preSetterFunctionNames = emptyList(),
        serializeItSelf = false,
        serializeAs = classId("kotlin", "Double"),
    ),
    ValueContainerClassInfo(
        classId = classId("androidx.compose.runtime.snapshots", "SnapshotStateList"),
        capturedFunctionNames = listOf(
            Name.identifier("add"),
            Name.identifier("addAll"),
            Name.identifier("clear"),
            Name.identifier("remove"),
            Name.identifier("removeAll"),
            Name.identifier("removeAt"),
            Name.identifier("set"),
            Name.identifier("replaceAll"),
        ),
        getterFunctionName = SpecialNames.THIS,
        setterFunctionName = Name.identifier("addAll"),
        preSetterFunctionNames = listOf(Name.identifier("clear")),
        serializeItSelf = true,
        serializeAs = classId("kotlin.collections", "List"),
    ),
    ValueContainerClassInfo(
        classId = classId("androidx.compose.runtime.snapshots", "SnapshotStateMap"),
        capturedFunctionNames = listOf(
            Name.identifier("clear"),
            Name.identifier("put"),
            Name.identifier("putAll"),
            Name.identifier("remove"),
            Name.identifier("set"),
        ),
        getterFunctionName = SpecialNames.THIS,
        setterFunctionName = Name.identifier("putAll"),
        preSetterFunctionNames = listOf(Name.identifier("clear")),
        serializeItSelf = true,
        serializeAs = classId("kotlin.collections", "Map"),
    ),
)
