[versions]
kotlinx-coroutines = "1.7.3"
kotlinx-serialization-json = "1.6.2"
auto-service = "1.1.1"
androidx-core = "1.12.0"
androidx-lifecycle = "2.6.2"
androidx-compose = "1.5.4"
robolectric = "4.11.1"
mockk = "1.13.8"
backintime = "1.0.0"

[libraries]
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
auto-service = { group = "com.google.auto.service", name = "auto-service", version.ref = "auto-service" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-core-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-core-ktx", version.ref = "androidx-lifecycle" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "androidx-compose" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
backintime = { group = "com.github.kitakkun.backintime", name = "library", version.ref = "backintime" }


