[versions]
flipper = "0.233.0"
kotlinx-coroutines = "1.7.3"
kotlinx-serialization-json = "1.6.2"

[libraries]
flipper = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
