name: Build and Test

on:
  push:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Publish to MavenLocal
        run: ./gradlew publishToMavenLocal

      - name: Run tests
        run: ./gradlew iosSimulatorArm64Test iosX64Test jvmTest testDebugUnitTest
