name: Build and Test Workflow

on: [ push, pull_request ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Publish required artifacts
        run: ./gradlew :backintime-plugin-common:publishToMavenLocal :backintime-compiler:publishToMavenLocal :backintime-core:publishToMavenLocal

      - name: Run JVM tests and Debug Unit Tests
        run: ./gradlew jvmTest testDebugUnitTest
