name: Build and Test

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Publish to MavenLocal
        run: ./gradlew publishToMavenLocal

      - name: Run tests
        run: ./gradlew iosSimulatorArm64Test iosX64Test jvmTest testDebugUnitTest

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"

      - name: generate js library for flipper
        run: |
          ./gradlew core:websocket:event:jsNodeProductionLibraryDistribution \
          tooling:model:jsNodeProductionLibraryDistribution \
          tooling:flipper-lib:jsNodeProductionLibraryDistribution
      - run: yarn install
        working-directory: flipper-plugin

      - run: yarn tsc
        working-directory: flipper-plugin
