name: Build and Test Workflow

on: [ push, pull_request ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and publish to Maven local (root)
        run: ./gradlew publishToMavenLocal

      - name: Build and publish to Maven local (back-in-time.library)
        run: ./gradlew -p library publishToMavenLocal

      - name: Run JVM tests and Debug Unit Tests (test directory)
        run: ./gradlew -p test jvmTest testDebugUnitTest
