on:
  push:
    tags:
      - '*'
jobs:
  get-kotlin-versions:
    runs-on: ubuntu-latest
    outputs:
      kotlin-versions: ${{ steps.make-kotlin-versions.outputs.value }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: make kotlin versions
        id: make-kotlin-versions
        run: |
          # split by "," and trim whitespaces
          versions=$(jq -R -s -c 'split(",") | map(gsub("^\\s+|\\s+$"; "")) | map(select(length > 0))' versions-root/supported-kotlin-versions.txt)
          echo "value=${versions}" >> $GITHUB_OUTPUT

  publish:
    needs: get-kotlin-versions
    runs-on: macos-latest
    strategy:
      matrix:
        kotlin: ${{ fromJson(needs.get-kotlin-versions.outputs.kotlin-versions) }}
    environment: Publication
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: publish to MavenCentral
        run: |
          versions=$(echo '${{ needs.get-kotlin-versions.outputs.kotlin-versions }}' | jq -r '.')
          first_version=$(echo $versions | jq -r '.[0]')
          
          if [ "${{ matrix.kotlin }}" == "$first_version" ]; then
            ./gradlew publishAllPublicationsToMavenCentralRepository
          else
            ./gradlew \
              compiler:k2:publishAllPublicationsToMavenCentralRepository \
              compiler:backend:publishAllPublicationsToMavenCentralRepository \
              compiler:cli:publishAllPublicationsToMavenCentralRepository \
              compiler:common:publishAllPublicationsToMavenCentralRepository
          fi
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{secrets.MAVEN_CENTRAL_USERNAME}}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{secrets.MAVEN_CENTRAL_PASSWORD}}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.GPG_KEY}}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{secrets.GPG_KEY_ID}}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{secrets.GPG_KEY_PASSWORD}}
          KOTLIN_VERSION: ${{matrix.kotlin}}
