on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: macos-latest
    environment: Publication
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: publish to MavenCentral
        run: ./gradlew publishAllPublicationsToMavenCentralRepository
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{secrets.MAVEN_CENTRAL_USERNAME}}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{secrets.MAVEN_CENTRAL_PASSWORD}}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.GPG_KEY}}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{secrets.GPG_KEY_PASSWORD}}
          KOTLIN_VERSION: ${{matrix.kotlin}}
