name: Review

on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Publish to MavenLocal
        run: ./gradlew publishToMavenLocal

      - name: Run tests
        run: ./gradlew iosSimulatorArm64Test iosX64Test jvmTest testDebugUnitTest

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Bundle
        run: |
          gem install bundler
          bundle install

      - name: Run Lint
        run: ./gradlew ktlintCheck

      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
