name: Review

on: pull_request

jobs:
  review-kotlin:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Publish to MavenLocal
        run: ./gradlew publishToMavenLocal

      - name: Run tests
        run: ./gradlew iosSimulatorArm64Test iosX64Test jvmTest testDebugUnitTest

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Bundle
        run: |
          gem install bundler
          bundle install

      - name: Run Lint
        run: ./gradlew ktlintCheck

      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger

  review-flipper:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"

      - run: yarn install
        working-directory: flipper-plugin

      - name: compile typescript
        run: yarn tsc
        working-directory: flipper-plugin
