name: Review

on: pull_request

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

  setupJDK:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

  setupRuby:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Bundle
        run: |
          gem install bundler
          bundle install

  runGradleTask:
    needs: [ checkout, setupRuby, setupJDK ]
    runs-on: ubuntu-latest
    steps:
      - name: Publish to MavenLocal
        run: ./gradlew publishToMavenLocal

      - name: Run allTests and ktlintCheck
        run: ./gradlew allTests ktlintCheck

  runDanger:
    needs: [ checkout, setupRuby, setupJDK, runGradleTask ]
    runs-on: ubuntu-latest
    steps:
      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
